### ISSUE TITLE
日本語環境以外でも動作するようにする

### ISSUE THREAD

**Issue by ruche7** [ruche7/VoiceroidUtil#148]
VOICEROID2は多言語対応しており、日本語環境以外にするとUI要素のテキストが変化する。
そのためテキストを使ってUI要素を特定する処理が軒並み失敗してしまう。
言語に依存しない情報からUI要素を特定できるようにする。

**Comment by KuromiAK** [comment]
`SaveFileDialogName = @"Save As";`にしたら一応en-USでも使えるようになった。

**Comment by ruche7** [comment]
本件、別ツール(非公開)では言語非依存でUI要素を操作するところまでできているのですが、モチベーションが上がらずフィードバックできていない状況です。
