### ISSUE TITLE
Expression Blend SDK未導入環境ではビルドできない

### ISSUE THREAD

**Issue by Tan90909090** [ruche7/VoiceroidUtil#175]
私のPCにはExpression Blend SDKを導入していないのですが、その状態でVoiceroidUtilをcloneして.slnをビルドしようとするとビルドエラーが発生しました。
C#ファイルでは`Behavior`クラスの使用箇所等で、XAMLファイルでは`<i:Interaction.Behaviors>`タグ等でエラーになっていました。
(これらのエラーによりクラス定義が不完全になって波及的に影響するためか、合計168箇所でエラーが起こりました。そのためエラー一覧は初略します)

Expression Blend SDKは現在OSSになっており、以下の方法で代替できるとのことです:
1. プロジェクトの参照から`System.Windows.Interactivity`と`Microsoft.Expression.Interactions`を除外
1. nugetから`Microsoft.Xaml.Behaviors.Wpf`を導入
1. xamlファイルのxmlns中の`http://schemas.microsoft.com/expression/2010/interactivity`と`http://schemas.microsoft.com/expression/2010/interactions`を、`http://schemas.microsoft.com/xaml/behaviors`に置換
1. csファイルの`System.Windows.Interactivity`名前空間を`Microsoft.Xaml.Behaviors`に置換 (出典元では置換前が`Microsoft.Xaml.Interactivity`等の表記ですが、誤記だと思います)

出典: 
- [Open Sourcing XAML Behaviors for WPF | .NET Blog](https://devblogs.microsoft.com/dotnet/open-sourcing-xaml-behaviors-for-wpf/)
- [System.Windows.Interactivityに代わるMicrosoft.Xaml.Behaviors.Wpf : わんちゅう日記](http://onechu312.blog.jp/archives/1074827701.html)
- [WPF のビヘイビアーが入ってる Blend SDK for Visual Studio が Visual Studio 2019 で消えた件について - かずきのBlog@hatena](https://blog.okazuki.jp/entry/2019/03/02/221827))

私の環境では、`RucheHomeLib`と`VoiceroidUtil`のプロジェクトについて上記の方法を取るとビルドが通るようになりました。
必要でしたらPull requestを送りたいと思っています。

**Comment by ruche7** [comment]
XamlBehaviors for WPF の存在自体は知っていた＆別ツール開発では使っていたのですが、VoiceroidUtilはつい最近までVS2017(with Expression Blend SDK)でビルドしており、VS2019に移行した際も手元の環境では特に問題とならなかったためスルーしていました。
近いうちに差し替えておきます。(この修正だけでアプリのリリースまではしない予定)
プルリクは無くても大丈夫です。ありがとうございます。

**Comment by ruche7** [comment]
対応しました。

ただ、 ReactiveProperty v3.6.0 が System.Windows.Interactivity.dll を利用しているため、パッケージには相変わらず System.Windows.Interactivity.dll が含まれます。
VoiceroidUtil が利用している機能からは参照されていないらしく、削除しても動きますが。

VoiceroidUtil のターゲットである .NET Framework 4.5 がサポートされないため、 ReactiveProperty を v4 以降にバージョンアップすることはできません。

**Comment by Tan90909090** [comment]
迅速な御返答ならびに御対応ありがとうございました！
